language: scala

scala:
  - 2.12.13
  - 2.13.5

jdk:
  - openjdk13

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt/boot/

script: sbt ++$TRAVIS_SCALA_VERSION test
